// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duhvsdgkfmcauefmabje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aHZzZGdrZm1jYXVlZm1hYmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjMxNDEsImV4cCI6MjA3MjA5OTE0MX0.8zklfAdmbWIZEz6A8IGs01Vn4956NGg0a5pCY7vfvXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});