// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnerbpfqqoramxvpdxbo.supabase.co";
// Use the anon (public) key from the same project as the backend, not the service role key
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZXJicGZxcW9yYW14dnBkeGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMDg1NTIsImV4cCI6MjA3ODY4NDU1Mn0.BiwJr6BbYP3NHshcKZvBtvkcaNTtB3rVLkq6wPgz-UI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});