-- ========================================
-- API App Database Schema for Supabase
-- ========================================

-- Main shares table
CREATE TABLE IF NOT EXISTS shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    content_type VARCHAR(10) NOT NULL CHECK (content_type IN ('text', 'file')),
    text_content TEXT,
    file_name VARCHAR(255),
    file_size BIGINT,
    file_url TEXT,
    view_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_shares_code ON shares(code);
CREATE INDEX IF NOT EXISTS idx_shares_created_at ON shares(created_at);
CREATE INDEX IF NOT EXISTS idx_shares_expires_at ON shares(expires_at);
CREATE INDEX IF NOT EXISTS idx_shares_is_active ON shares(is_active);

-- Optional: Function to get share by code with business logic
CREATE OR REPLACE FUNCTION get_share_by_code(share_code TEXT)
RETURNS TABLE (
    id BIGINT,
    code VARCHAR,
    content_type VARCHAR,
    text_content TEXT,
    file_name VARCHAR,
    file_size BIGINT,
    file_url TEXT,
    view_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Increment view count
    UPDATE shares 
    SET view_count = view_count + 1 
    WHERE code = UPPER(share_code) 
    AND (expires_at IS NULL OR expires_at > NOW())
    AND is_active = TRUE;
    
    -- Return the share record
    RETURN QUERY
    SELECT *
    FROM shares 
    WHERE code = UPPER(share_code) 
    AND (expires_at IS NULL OR expires_at > NOW())
    AND is_active = TRUE;
END;
$$;

-- Alternative function with parameter name matching what the code expects
CREATE OR REPLACE FUNCTION get_share_by_code(_code TEXT)
RETURNS TABLE (
    id BIGINT,
    code VARCHAR,
    content_type VARCHAR,
    text_content TEXT,
    file_name VARCHAR,
    file_size BIGINT,
    file_url TEXT,
    view_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Increment view count
    UPDATE shares 
    SET view_count = view_count + 1 
    WHERE code = UPPER(_code) 
    AND (expires_at IS NULL OR expires_at > NOW())
    AND is_active = TRUE;
    
    -- Return the share record
    RETURN QUERY
    SELECT *
    FROM shares 
    WHERE code = UPPER(_code) 
    AND (expires_at IS NULL OR expires_at > NOW())
    AND is_active = TRUE;
END;
$$;
